import type { CategoryDefinition } from '../../types/subject.ts';

/** Humanoid characters — the default category, and the one the component-count model was built around. */
export const CHARACTER: CategoryDefinition = {
  label: 'Humanoid Character',
  fields: [
    {
      key: 'species',
      label: 'Species / Archetype',
      tooltip:
        'The base organism or entity type, and the strongest single driver of the whole sheet: it fixes the skeletal layout and the proportions every other field is drawn on top of. Free text is accepted — the list is a starting point, not a constraint.',
      options: [
        'Human',
        'Cybernetic Cyborg',
        'High Elf',
        'Orc Warrior',
        'Demonic Fiend',
        'Android',
        'Steampunk Automaton',
        'Celestial Angel',
        'Necromancer Lich',
        'Void Stalker',
        'Draconian Berserker',
        'Gnome Tinker',
        'Vampire Lord',
        'Space Marine',
        'Shadow Assassin',
        'Mutant Scavenger',
      ],
    },
    {
      key: 'gender',
      label: 'Gender / Presentation',
      tooltip:
        'Body presentation and shape language. It guides shoulder width, waist ratio and torso curvature across every component, and lands hardest on the torso and pelvis pieces, where the silhouette is established.',
      options: [
        'Androgynous / Neutral',
        'Feminine',
        'Masculine',
        'Non-Binary',
        'Agender',
        'Demonic Sovereign',
        'Synthetic Construct',
        'Feminine Arcane',
        'Masculine Brute',
        'Cyber-Armoured Form',
      ],
    },
    {
      key: 'age',
      label: 'Age Presentation',
      tooltip:
        'Apparent age, read as posture, surface condition and facial structure. An older presentation brings stance stiffness and wear with it; an ageless synthetic one suppresses both and keeps surfaces clean.',
      options: [
        'Young Adult (20s)',
        'Mature / Veteran (40s)',
        'Ancient / Venerable',
        'Ageless Synthetic',
        'Teenage Prodigy',
        'Centuries-Old Immortal',
        'Freshly Awakened',
        'Corroded Ancient',
      ],
    },
    {
      key: 'role',
      label: 'Role / Class',
      tooltip:
        'The combat or utility specialisation. It decides where visual weight goes — a rogue reads light and close to the body, a paladin heavy and outward — so it shapes the limb components as much as the gear on them.',
      options: [
        'Katana Specialist',
        'Heavy Mech Marine',
        'Arcane Sorceress',
        'Rogue Assassin',
        'Bounty Hunter',
        'Paladin',
        'Gunslinger Outlaw',
        'Druid Shapeshifter',
        'Flame Elementalist',
        'Cyber Monk',
        'Shield Guardian',
        'Alchemist',
        'Sniper Ranger',
        'Tech-Priest',
      ],
    },
    {
      key: 'setting',
      label: 'Setting / Theme',
      tooltip:
        'The world the subject belongs to. It enforces epoch-appropriate design across every part at once, which is what stops a plate gauntlet turning up on a cyberpunk figure — set it before reaching for the per-part detail fields.',
      options: [
        'Cyberpunk Dystopia',
        'Dark Fantasy',
        'Grimdark Sci-Fi',
        'Steampunk Retro',
        'Post-Apocalyptic',
        'Solar-Punk Utopia',
        'Eldritch Cosmic Horror',
        'Dieselpunk Trenches',
        'Nether Underworld',
        'Underwater Hydro-Station',
        'Feudal Japan Cyber',
        'High Magic High Renaissance',
      ],
    },
    {
      key: 'build',
      label: 'Build & Proportions',
      tooltip:
        'Weight, muscularity and width. This sets the bounding-box volume each component occupies, so it decides how many pixels a limb actually gets once the sheet is packed into an atlas cell.',
      options: [
        'Athletic & Slender',
        'Heavy Armoured Tank',
        'Lethal Agile',
        'Stocky & Robust',
        'Tall & Ethereal',
        'Towering Colossus',
        'Compact Dwarf',
        'Ethereal Floating',
        'Heavy Exosuit Frame',
        'Skeletal Slender',
      ],
    },
    {
      key: 'silhouette',
      label: 'Overall Silhouette',
      tooltip:
        'The outline the figure reads as at a glance. It is what decides whether the sprite is recognisable at gameplay distance: a distinctive edge profile survives downscaling long after the interior detail has gone.',
      options: [
        'Dynamic Sharp Edges',
        'Bulky Plated Layers',
        'Flowing Robes & Cape',
        'Sleek Aerodynamic',
        'Spiked Shadow Outline',
        'Asymmetrical Pauldrons',
        'Broad-Shouldered Fortress',
        'Floating Orbs & Ribbon',
        'Horned Spiked Silhouette',
      ],
    },
    {
      key: 'face_head',
      label: 'Face, Hair & Head',
      tooltip:
        'Expression, hair, helmets and visors — everything shaping the isolated head component and its directional variants. The head is usually the smallest piece and the most looked at, so one strong feature beats fine detail here.',
      options: [
        'Neon Visor & Undercut',
        'Full Enclosed Helmet',
        'Hooded Mask & Glowing Eyes',
        'Braided Hair & Warpaint',
        'Horned Crown & Mask',
        'Monocular Cyber Eye',
        'Skeletal Skull Face',
        'Ornate Crested Visor',
        'Cyborg Jawplate & Goggles',
      ],
    },
    {
      key: 'anatomy',
      label: 'Anatomy Base',
      tooltip:
        'The skeleton the component breakdown is derived from. STANDARD HUMANOID yields the default 9 core and 34 limb components; a winged, tailed or four-armed base adds dedicated slots of its own rather than fusing the extra parts onto existing ones.',
      options: [
        'STANDARD HUMANOID',
        'HUMANOID WITH WINGS',
        'TAILED HUMANOID',
        'QUADRUPED TAUR',
        'CENTAUR LOWER BODY',
        'FOUR-ARMED HUMANOID',
        'SERPENT LOWER BODY',
      ],
    },
    {
      key: 'clothing',
      label: 'Clothing / Armour',
      tooltip:
        'Garments and protective plating, drawn into the limb and torso surfaces rather than laid over them as separate pieces. Anything that has to move independently belongs in Additional Genuine Anatomy or a socket instead.',
      options: [
        'Tactical Kevlar & Plates',
        'Gothic Plate Armour',
        'Enchanted Runed Robes',
        'Leather Duster Coat',
        'Reinforced Exo-Pads',
        'Ceremonial Silk & Gold',
        'Nano-Weave Bodysuit',
        'Spiked Bone Armor',
        'Industrial Hazard Suit',
      ],
    },
    {
      key: 'worn_details',
      label: 'Integrated Worn Details',
      tooltip:
        'Holsters, pouches, cabling and belts, attached cleanly to the part each one sits on. “Integrated” is the operative word: loose clutter that spans two components cannot be cut apart without tearing one of them.',
      options: [
        'Holstered Sidearm & Pouch',
        'Shoulder Pauldrons & Cloak',
        'Fibre-Optic Cabling',
        'Ammunition Belts',
        'Scabbard & Strap Rig',
        'Scroll Tubes & Flasks',
        'Energy Battery Backpack',
        'Tattered Cape & Chain',
        'Medic Utility Pack',
      ],
    },
    {
      key: 'primary_colours',
      label: 'Primary Colours',
      tooltip:
        'The dominant share of the palette — roughly 60% — applied as global albedo across every component. Naming two colours reads more reliably than one, because it gives the generator a value contrast to hold the sheet together with.',
      options: [
        'Matte Charcoal Black & Gunmetal',
        'Royal Navy & Deep Silver',
        'Crimson Red & Black',
        'Emerald Green & Tan',
        'Midnight Violet & Indigo',
        'Sand Beige & Rust',
        'Pearl White & Chrome',
        'Deep Obsidian & Gold',
      ],
    },
    {
      key: 'accent_colours',
      label: 'Accent Colours',
      tooltip:
        'The high-contrast remainder — roughly 20% — for energy lines, eyes, trim and glows. A hex code pins the colour far more tightly than a name does, and the swatch beside this field previews whatever it recognises.',
      options: [
        'Cyan Neon #06B6D4',
        'Polished Gold #F59E0B',
        'Electric Violet',
        'Safety Crimson',
        'Toxic Acid Green',
        'Plasma Cyan',
        'Molten Copper',
        'Spectral Rose',
        'Laser Yellow #EAB308',
      ],
    },
    {
      key: 'materials',
      label: 'Materials & Surfaces',
      tooltip:
        'What the surfaces are made of, and therefore how light reads off them: metal takes a hard specular edge, cloth stays matte. It still matters under flat neutral lighting, because the material is what decides the shading steps.',
      options: [
        'Reinforced Composites & Alloy',
        'Burnished Steel & Leather',
        'Woven Silk & Runic Crystals',
        'Weathered Carbon Fibre',
        'Damascus Steel & Dragon Scale',
        'Polished Brass & Glass',
        'Etched Obsidian Plate',
        'Synthetic Polymer',
      ],
    },
    {
      key: 'exclusions',
      label: 'Explicit Exclusions',
      tooltip:
        'Negative rules compiled into the prompt to keep unrequested things out of the sheet. Floor shadows and stray props are the usual offenders — both fuse a component to its background and leave nothing clean to key out.',
      options: [
        'No weapons, no floor shadows',
        'No oversized pauldrons',
        'No cape, no facial features',
        'No glowing trails',
        'No floor terrain, no text labels',
        'No background clutter, no pets',
      ],
    },
    {
      key: 'additional_anatomy',
      label: 'Additional Genuine Anatomy',
      tooltip:
        'Extra anatomy — a tail, a wing pair, auxiliary arms — requested as its own dedicated sprite slots so it can be animated separately from the body. Leave this as NONE unless the part genuinely needs to move on its own.',
      options: [
        'NONE',
        'Prehensile Cyber Tail',
        'Mechanical Wing Pair',
        'Dual Auxiliary Arms',
        'Serpentine Tail',
        'Feathered Archangel Wings',
        'Demon Horn Pair & Tail',
      ],
    },
  ],
};
