import { NO_ADDITIONAL_ANATOMY } from '../anatomy.ts';
import {
  ASSEMBLY_BASE_CHOOSES_THE_SHEETS,
  HEX_CODE_PINS_THE_HUE,
  SUBJECT_TYPE_ADDS_NO_COMPONENTS,
} from '../guidanceSentences.ts';
import type { CategoryDefinition } from '../../types/subject.ts';

/** Humanoid characters — the default category, and the one the component-count model was built around. */
export const CHARACTER: CategoryDefinition = {
  label: 'Humanoid Character',
  article: 'a',
  fields: [
    {
      key: 'species',
      label: 'Species / Archetype',
      tooltip:
        'The base organism or entity type, and the strongest single influence on the figure: it sets the body shape and proportions every other field is drawn on. You can type your own; the list is only a starting point.\n\n' +
        SUBJECT_TYPE_ADDS_NO_COMPONENTS,
      options: [
        'Human',
        'Cybernetic Cyborg',
        'High Elf',
        'Orc Warrior',
        'Demonic Fiend',
        'Android',
        'Steampunk Automaton',
        'Celestial Angel',
        'Necromancer Lich',
        'Void Stalker',
        'Draconian Berserker',
        'Gnome Tinker',
        'Vampire Lord',
        'Space Marine',
        'Shadow Assassin',
        'Mutant Scavenger',
        'Beastfolk Ranger',
        'Plant-Grafted Dryad',
        'Amphibious Deep-Dweller',
        'Porcelain Doll Construct',
        'Ashen Revenant',
        'Fungal Myconid',
        'Sentient Slime Humanoid',
        'Stone-Skinned Golemkin',
        'Feathered Avian Folk',
        'Chitin-Plated Insectkin',
        'Half-Giant Highlander',
        'Ordinary Villager',
      ],
    },
    {
      key: 'gender',
      label: 'Gender / Presentation',
      tooltip:
        'Body presentation and shape language. It guides shoulder width, waist ratio and torso curvature across every component, and lands hardest on the torso and pelvis, where the silhouette is set.',
      options: [
        'Androgynous / Neutral',
        'Feminine',
        'Masculine',
        'Non-Binary',
        'Agender',
        'Demonic Sovereign',
        'Synthetic Construct',
        'Feminine Arcane',
        'Masculine Brute',
        'Cyber-Armoured Form',
        'Encased — Form Unreadable',
        'Hive-Linked Collective',
      ],
    },
    {
      key: 'age',
      label: 'Age Presentation',
      tooltip:
        'Apparent age, read as posture, surface condition and facial structure. An older presentation brings a stiffer stance and wear; an ageless synthetic one suppresses both and keeps surfaces clean.',
      options: [
        'Young Adult (20s)',
        'Mature / Veteran (40s)',
        'Ancient / Venerable',
        'Ageless Synthetic',
        'Teenage Prodigy',
        'Centuries-Old Immortal',
        'Freshly Awakened',
        'Corroded Ancient',
        'Child (Under 12)',
        'Elderly & Stooped (70s)',
        'Middle-Aged & Weathered (50s)',
        'Prime Of Life (30s)',
        'Ageless Nature Spirit',
      ],
    },
    {
      key: 'role',
      label: 'Role / Class',
      tooltip:
        'The combat or utility specialisation. It decides where visual weight goes, so a rogue reads light and close to the body and a paladin heavy and outward. It shapes the limbs as much as the gear on them.',
      options: [
        'Katana Specialist',
        'Heavy Mech Marine',
        'Arcane Sorceress',
        'Rogue Assassin',
        'Bounty Hunter',
        'Paladin',
        'Gunslinger Outlaw',
        'Druid Shapeshifter',
        'Flame Elementalist',
        'Cyber Monk',
        'Shield Guardian',
        'Alchemist',
        'Sniper Ranger',
        'Tech-Priest',
        'Deep-Pressure Salvager',
        'Message Courier',
        'Field Medic',
        'Cartographer / Surveyor',
        'Beast Tamer',
        'Saboteur Demolitionist',
        'Innkeeper / Merchant',
        'Farmhand / Homesteader',
        'Plague Doctor',
        'Blind Oracle',
        'Wandering Ronin',
      ],
    },
    {
      key: 'setting',
      label: 'Setting / Theme',
      tooltip:
        'The world the subject belongs to. It keeps every part true to one epoch, which stops a plate gauntlet turning up on a cyberpunk figure, so set it before the per-part detail fields.',
      options: [
        'Cyberpunk Dystopia',
        'Dark Fantasy',
        'Grimdark Sci-Fi',
        'Steampunk Retro',
        'Post-Apocalyptic',
        'Solar-Punk Utopia',
        'Eldritch Cosmic Horror',
        'Dieselpunk Trenches',
        'Nether Underworld',
        'Underwater Hydro-Station',
        'Feudal Japan Cyber',
        'High Magic High Renaissance',
        'Sunbaked Desert Caravan',
        'Frozen Tundra Expedition',
        'Victorian Occult London',
        'Mesoamerican Jungle Empire',
        'Orbital Ring Habitat',
        'Wild West Frontier',
        'Nautical Age Of Sail',
        'Cosy Pastoral Farmland',
        'Ancient Forest Grove',
        'Mountain Monastery Terraces',
        'Plague-Struck Old City',
      ],
    },
    {
      key: 'build',
      label: 'Build & Proportions',
      tooltip:
        'Weight, muscularity and width. It sets the volume each component’s bounding box holds, and so how many pixels a limb gets once the sheet is packed into an atlas cell.',
      options: [
        'Athletic & Slender',
        'Heavy Armoured Tank',
        'Lethal Agile',
        'Stocky & Robust',
        'Tall & Ethereal',
        'Towering Colossus',
        'Compact Dwarf',
        'Ethereal Floating',
        'Heavy Exosuit Frame',
        'Skeletal Slender',
        'Wiry & Underfed',
        'Broad Peasant Frame',
        'Child-Scaled Chibi',
        'Long-Limbed Insectile',
        'Lean Ascetic Frame',
        'Shifting Half-Beast Mass',
      ],
    },
    {
      key: 'silhouette',
      label: 'Overall Silhouette',
      tooltip:
        'The outline the figure reads as at a glance. It decides whether the sprite is recognisable at gameplay distance, because a distinctive edge survives downscaling long after the interior detail has gone.',
      options: [
        'Dynamic Sharp Edges',
        'Bulky Plated Layers',
        'Flowing Robes & Cape',
        'Sleek Aerodynamic',
        'Spiked Shadow Outline',
        'Asymmetrical Pauldrons',
        'Broad-Shouldered Fortress',
        // `Floating Orbs & Ribbon` and `Head And Shoulders Only` were here (issue #284). No CHARACTER
        // sheet draws an orb floating free of the body, and every one draws legs and feet below the
        // shoulders; PORTRAIT is the category that draws a bust.
        'Horned Spiked Silhouette',
        'Hunched Cloaked Bundle',
        'Wide Conical Hat & Robe',
        'Trailing Ribbon Streamers',
        'Long Duster & Wide-Brim Hat',
        'Ragged Foliage & Antler Crown',
        'Draped Ghillie Fronds',
        'Layered Monastic Wrap',
      ],
    },
    {
      key: 'face_head',
      label: 'Face, Hair & Head',
      tooltip:
        'Expression, hair, helmets and visors: everything that shapes the head component and its directional variants. The head is usually the smallest piece and the most looked at, so one strong feature beats fine detail.',
      options: [
        'Neon Visor & Undercut',
        'Full Enclosed Helmet',
        'Hooded Mask & Glowing Eyes',
        'Braided Hair & Warpaint',
        'Horned Crown & Mask',
        'Monocular Cyber Eye',
        'Skeletal Skull Face',
        'Ornate Crested Visor',
        'Cyborg Jawplate & Goggles',
        'Brass Porthole Helm & Lamp',
        'Freckles, Loose Curls & Ink Smudges',
        'Plague Doctor Beak Mask',
        'Blindfold & Ritual Scar',
        'Antlered Circlet',
        'Menpō Mask & Topknot',
        'Wide-Brim Hat & Dust Bandana',
        'Ember-Lit Hair & Ash Crown',
        'Shaven Head & Circuit Tattoos',
        'Leaf-Woven Circlet & Green Eyes',
        'Ghillie Hood & Face Paint',
        'Hooded Cowl & Mechadendrites',
        'Welding Goggles & Soot-Stained Face',
        'Straw Hat & Sun-Bleached Hair',
        'Brass Spectacles & Ink-Stained Brow',
        'Wild Mane & Scarred Cheek',
        'Rolled Headscarf & Weary Smile',
        'Halo Ring & Blank Serene Face',
      ],
      oneSidedOptions: {
        'Neon Visor & Undercut': 'undercut',
        'Monocular Cyber Eye': 'monocular cyber eye',
        'Wild Mane & Scarred Cheek': 'scarred cheek',
      },
    },
    {
      key: 'anatomy',
      label: 'Anatomy Base',
      tooltip:
        'The skeleton the figure is drawn on. A winged, tailed, four-armed, taur, centaur or serpent base draws its wings, tail, second arms or lower body as components of their own, and a digitigrade base draws feet that stand on their toes.\n\n' +
        ASSEMBLY_BASE_CHOOSES_THE_SHEETS +
        '\n\nA part no base draws goes in Additional Genuine Anatomy, which adds a sprite slot for each piece you name.',
      options: [
        'Standard Humanoid',
        'Humanoid With Wings',
        'Tailed Humanoid',
        'Quadruped Taur',
        'Centaur Lower Body',
        'Four-Armed Humanoid',
        'Serpent Lower Body',
        // `Bust — Head, Neck And Shoulders` was here and is not any more. It was added on 2026-08-08,
        // a fortnight before PORTRAIT became a category of its own, and it argued for itself on a
        // premise that has never been true: that the assembly base reshapes the inventory, so a
        // portrait base would take the arm and leg entries off the sheet. It does not — see
        // `sheetPlans/portrait.ts` — so every CHARACTER sheet went on ordering five torsos, five
        // pelvises and thirty-four arm and leg segments for a subject section 1 called a head, neck
        // and shoulders. PORTRAIT offers `Framing & Crop: Head Only` and is where that sheet is now
        // made.
        'Chibi Super-Deformed',
        'Humanoid With Prosthetic Limb',
        'Hybrid Half-Beast Form',
        'Digitigrade Beastfolk Legs',
      ],
      oneSidedOptions: {
        'Humanoid With Prosthetic Limb': 'prosthetic limb',
      },
    },
    {
      key: 'clothing',
      label: 'Clothing / Armour',
      tooltip:
        'Garments and protective plating, drawn into the limb and torso surfaces rather than laid over them as separate pieces. Anything that has to move on its own belongs in Additional Genuine Anatomy or a socket.',
      options: [
        'Tactical Kevlar & Plates',
        'Gothic Plate Armour',
        'Enchanted Runed Robes',
        'Leather Duster Coat',
        'Reinforced Exo-Pads',
        'Ceremonial Silk & Gold',
        'Nano-Weave Bodysuit',
        'Spiked Bone Armor',
        'Industrial Hazard Suit',
        'Patched Wool & Oilskin',
        'Deep-Sea Pressure Suit',
        'Ceremonial Feathered Regalia',
        'Surgeon’s Apron & Gauntlets',
        'Beekeeper Veil & Canvas',
        'Bark, Hide & Living Moss',
        'Lacquered Lamellar & Kimono',
        'Ghillie Wrap & Camouflage Cloak',
        'Saffron Wrapped Robes & Circuitry',
        'Hooded Tech-Vestments & Cabling',
        'Rolled Sleeves & Publican’s Apron',
        'Travelling Leathers & Light Pack',
        'Waxed Plague Coat & Gloves',
        'Layered Pelts & Fur Mantle',
      ],
    },
    {
      key: 'worn_details',
      label: 'Integrated Worn Details',
      tooltip:
        'Holsters, pouches, cabling and belts, each attached cleanly to the part it sits on. Loose clutter that spans two components cannot be cut apart without tearing one of them, so keep every detail _integrated_.',
      options: [
        'Holstered Sidearm & Pouch',
        'Shoulder Pauldrons & Cloak',
        'Fibre-Optic Cabling',
        'Ammunition Belts',
        'Scabbard & Strap Rig',
        'Scroll Tubes & Flasks',
        'Energy Battery Backpack',
        'Tattered Cape & Chain',
        'Medic Utility Pack',
        'Umbilical Hose & Ballast Weights',
        'Map Tube & Brass Compass',
        'Bandolier Of Vials',
        'Prayer Beads & Charm Bells',
        'Clockwork Prosthetic Hand',
        'Herb Pouches & Bone Fetishes',
        'Whip Coil & Leash Rings',
        'Charge Satchel & Fuse Coils',
        'Coin Purse & Tally Ledger',
        'Tool Belt & Seed Pouch',
        'Rangefinder & Spotting Scope',
        'Incense Censer & Wax Seals',
        'Rolled Blanket & Cook Pot',
        'Six-Gun Belt & Spur Straps',
      ],
      oneSidedOptions: {
        'Holstered Sidearm & Pouch': 'holstered sidearm and pouch',
        'Scabbard & Strap Rig': 'scabbard',
        'Bandolier Of Vials': 'bandolier of vials',
        'Clockwork Prosthetic Hand': 'clockwork prosthetic hand',
      },
    },
    {
      key: 'primary_colours',
      label: 'Primary Colours',
      tooltip:
        'The dominant share of the palette, roughly 60%, applied as the base colour of every component. Two colours read more reliably than one, because they give the generator a value contrast to hold the sheet together.',
      options: [
        'Matte Charcoal Black & Gunmetal',
        'Royal Navy & Deep Silver',
        'Crimson Red & Black',
        'Emerald Green & Tan',
        'Midnight Violet & Indigo',
        'Sand Beige & Rust',
        'Pearl White & Chrome',
        'Deep Obsidian & Gold',
        'Verdigris Copper & Deep Teal',
        'Bone White & Ash Grey',
        'Moss Green & Oxblood',
        'Ink Black & Parchment',
        'Bark Brown & Fern Green',
        'Saffron Ochre & Warm Grey',
        'Dust Tan & Faded Denim',
        'Slate Blue & Weathered Oak',
      ],
    },
    {
      key: 'accent_colours',
      label: 'Accent Colours',
      tooltip:
        'The high-contrast remainder, roughly 20%, for energy lines, eyes, trim and glows. ' +
        HEX_CODE_PINS_THE_HUE,
      options: [
        'Cyan Neon #06B6D4',
        'Polished Gold #F59E0B',
        'Electric Violet',
        'Safety Crimson',
        'Toxic Acid Green',
        'Plasma Cyan',
        'Molten Copper',
        'Spectral Rose',
        'Laser Yellow #EAB308',
        'Sodium Lamp Amber',
        'Bioluminescent Teal',
        'Ember Orange #F97316',
        'Ultraviolet Bloom #8B5CF6',
        'Fresh Sap Green',
        'Tarnished Brass',
      ],
    },
    {
      key: 'materials',
      label: 'Materials & Surfaces',
      tooltip:
        'What the surfaces are made of, and so how light reads off them: metal takes a hard specular edge, cloth stays matte. It matters even under flat neutral lighting, because the material decides the shading steps.',
      options: [
        'Reinforced Composites & Alloy',
        'Burnished Steel & Leather',
        'Woven Silk & Runic Crystals',
        'Weathered Carbon Fibre',
        'Damascus Steel & Dragon Scale',
        'Polished Brass & Glass',
        'Etched Obsidian Plate',
        'Synthetic Polymer',
        'Riveted Brass & Barnacled Canvas',
        'Waxed Canvas & Boiled Leather',
        'Lacquered Wood & Rice Paper',
        'Woven Reed & Bone',
        'Living Bark & Woven Vine',
        'Homespun Linen & Rough Wool',
        'Ash-Scorched Iron & Cinder',
        'Beeswax, Horn & Pale Bone',
      ],
    },
    {
      key: 'exclusions',
      label: 'Explicit Exclusions',
      tooltip:
        'Negative rules in the prompt that keep unrequested things off the sheet. Floor shadows and stray props are the usual offenders: both fuse a component to its background and leave nothing clean to key out.',
      options: [
        // First, and that is a decision rather than an ordering: `defaultSubjectFor` builds the
        // subject a category switch installs out of every pool's leading option, so this one is
        // read against `Holstered Sidearm & Pouch` — the leading `worn_details`. `No weapons, no
        // floor shadows` here makes the default CHARACTER subject ask for a sidearm in section 1
        // and remove it in section 8. Floor shadows alone is also the first of the two this
        // field's own tooltip calls the usual offenders, and the weapons ban keeps its place one
        // line down for whoever wants it.
        'No floor shadows',
        'No weapons, no floor shadows',
        'No oversized pauldrons',
        'No cape, no facial features',
        'No glowing trails',
        'No floor terrain, no text labels',
        'No background clutter, no pets',
        'No weapons, no floor shadows, no bubbles, no water caustics',
        // `No hands, no torso below the collarbone, no dialogue frame, no text` was here and is not
        // any more, for the reason the portrait base above went: it is a portrait's ban on a
        // category whose every sheet orders a torso, and three of the four order hands. Section 8's
        // closing paragraph kept it from breaking a sheet — where section 4 lists an entry this
        // section excludes, the entry is drawn — which only meant the prompt overruled the reader's
        // own ban on every component it named. “Dialogue frame” names a surface no CHARACTER sheet
        // has either. PORTRAIT offers `No name plate, caption or speech bubble` instead.
        'No baked shadow of any kind, no assembled figure, no equipment in the sockets',
        'No motion blur, no speed lines',
        'No signature, no watermark, no colour swatch strip',
        'No limb cropped at the sheet edge',
        'No animal companion, no shifted beast form',
        'No lit flame, no smoke plume',
        'No held tool, no carried crop or basket',
        'No mount, no reins, no saddle',
      ],
    },
    {
      key: 'additional_anatomy',
      label: 'Additional Genuine Anatomy',
      tooltip:
        'Extra anatomy, such as horns, a tail, a wing pair or auxiliary arms, each requested as its own sprite slot so you can animate it apart from the body. Anatomy Base already draws the wings, tail or second arms its own body has.\n\n' +
        'List them with commas and `×N` for how many of each: “Demon Horn ×2, Tail ×1” names three pieces, each drawn at every facing the sheet covers. That is fifteen components on a five-view directional core, or three on a single-facing sheet.',
      options: [
        NO_ADDITIONAL_ANATOMY,
        'Prehensile Cyber Tail ×1',
        'Mechanical Wing ×2',
        'Auxiliary Arm ×2',
        'Serpentine Tail ×1',
        'Feathered Archangel Wing ×2',
        'Demon Horn ×2, Tail ×1',
        'Prosthetic Arm ×1',
        'Antler Rack ×2',
        'Floating Rune Sigil ×3',
        'Mainspring Escapement ×1, Satchel ×1',
        // The portrait case: a dialogue sheet's components are the *readings* of one face, and this is
        // the field that makes the count and the inventory say so.
        'Neutral Expression ×1, Joyful ×1, Angry ×1, Afraid ×1, Wounded ×1, Sceptical ×1',
        'Beast Ear ×2, Bushy Tail ×1',
        'Ivy Vine Wrap ×2',
        'Mechadendrite Arm ×3',
        'Insect Wing ×4',
      ],
    },
  ],
};
