import { NO_ADDITIONAL_ANATOMY } from '../anatomy.ts';
import type { CategoryDefinition } from '../../types/subject.ts';

/** Humanoid characters — the default category, and the one the component-count model was built around. */
export const CHARACTER: CategoryDefinition = {
  label: 'Humanoid Character',
  fields: [
    {
      key: 'species',
      label: 'Species / Archetype',
      tooltip:
        'Defines the base organism or entity type. Sets fundamental skeletal structure and proportions for AI image generation.',
      options: [
        'Human',
        'Cybernetic Cyborg',
        'High Elf',
        'Orc Warrior',
        'Demonic Fiend',
        'Android',
        'Steampunk Automaton',
        'Celestial Angel',
        'Necromancer Lich',
        'Void Stalker',
        'Draconian Berserker',
        'Gnome Tinker',
        'Vampire Lord',
        'Space Marine',
        'Shadow Assassin',
        'Mutant Scavenger',
      ],
    },
    {
      key: 'gender',
      label: 'Gender / Presentation',
      tooltip:
        'Controls biological presentation or body shape features. Guides waist ratio, shoulder width, and torso curvature.',
      options: [
        'Androgynous / Neutral',
        'Feminine',
        'Masculine',
        'Non-Binary',
        'Agender',
        'Demonic Sovereign',
        'Synthetic Construct',
        'Feminine Arcane',
        'Masculine Brute',
        'Cyber-Armoured Form',
      ],
    },
    {
      key: 'age',
      label: 'Age Presentation',
      tooltip:
        'Establishes age, posture stiffness, and surface detail complexity. Influences skin texture, stance, and face aging.',
      options: [
        'Young Adult (20s)',
        'Mature / Veteran (40s)',
        'Ancient / Venerable',
        'Ageless Synthetic',
        'Teenage Prodigy',
        'Centuries-Old Immortal',
        'Freshly Awakened',
        'Corroded Ancient',
      ],
    },
    {
      key: 'role',
      label: 'Role / Class',
      tooltip:
        'Defines combat or utility specialization. Influences visual gear focus (e.g., rogue vs heavy paladin).',
      options: [
        'Katana Specialist',
        'Heavy Mech Marine',
        'Arcane Sorceress',
        'Rogue Assassin',
        'Bounty Hunter',
        'Paladin',
        'Gunslinger Outlaw',
        'Druid Shapeshifter',
        'Flame Elementalist',
        'Cyber Monk',
        'Shield Guardian',
        'Alchemist',
        'Sniper Ranger',
        'Tech-Priest',
      ],
    },
    {
      key: 'setting',
      label: 'Setting / Theme',
      tooltip:
        'Establishes environmental context and visual genre aesthetics. Enforces epoch-appropriate design rules.',
      options: [
        'Cyberpunk Dystopia',
        'Dark Fantasy',
        'Grimdark Sci-Fi',
        'Steampunk Retro',
        'Post-Apocalyptic',
        'Solar-Punk Utopia',
        'Eldritch Cosmic Horror',
        'Dieselpunk Trenches',
        'Nether Underworld',
        'Underwater Hydro-Station',
        'Feudal Japan Cyber',
        'High Magic High Renaissance',
      ],
    },
    {
      key: 'build',
      label: 'Build & Proportions',
      tooltip:
        'Determines weight, muscularity, and physical width scale. Controls bounding-box volume per sprite component.',
      options: [
        'Athletic & Slender',
        'Heavy Armoured Tank',
        'Lethal Agile',
        'Stocky & Robust',
        'Tall & Ethereal',
        'Towering Colossus',
        'Compact Dwarf',
        'Ethereal Floating',
        'Heavy Exosuit Frame',
        'Skeletal Slender',
      ],
    },
    {
      key: 'silhouette',
      label: 'Overall Silhouette',
      tooltip: 'Focuses key edge features. Important for readability in 2D platformers and top-down games.',
      options: [
        'Dynamic Sharp Edges',
        'Bulky Plated Layers',
        'Flowing Robes & Cape',
        'Sleek Aerodynamic',
        'Spiked Shadow Outline',
        'Asymmetrical Pauldrons',
        'Broad-Shouldered Fortress',
        'Floating Orbs & Ribbon',
        'Horned Spiked Silhouette',
      ],
    },
    {
      key: 'face_head',
      label: 'Face, Hair & Head',
      tooltip:
        'Specifies facial expression, hair style, helmets, or visors. Shapes the isolated head component variants.',
      options: [
        'Neon Visor & Undercut',
        'Full Enclosed Helmet',
        'Hooded Mask & Glowing Eyes',
        'Braided Hair & Warpaint',
        'Horned Crown & Mask',
        'Monocular Cyber Eye',
        'Skeletal Skull Face',
        'Ornate Crested Visor',
        'Cyborg Jawplate & Goggles',
      ],
    },
    {
      key: 'anatomy',
      label: 'Anatomy Base',
      tooltip:
        'Configures component breakdown logic. Standard humanoid generates default 9-core + 34-limb components.',
      options: [
        'STANDARD HUMANOID',
        'HUMANOID WITH WINGS',
        'TAILED HUMANOID',
        'QUADRUPED TAUR',
        'CENTAUR LOWER BODY',
        'FOUR-ARMED HUMANOID',
        'SERPENT LOWER BODY',
      ],
    },
    {
      key: 'clothing',
      label: 'Clothing / Armour',
      tooltip:
        'Specifies garments and protective plating integrated directly into limb/torso component surfaces.',
      options: [
        'Tactical Kevlar & Plates',
        'Gothic Plate Armour',
        'Enchanted Runed Robes',
        'Leather Duster Coat',
        'Reinforced Exo-Pads',
        'Ceremonial Silk & Gold',
        'Nano-Weave Bodysuit',
        'Spiked Bone Armor',
        'Industrial Hazard Suit',
      ],
    },
    {
      key: 'worn_details',
      label: 'Integrated Worn Details',
      tooltip:
        'Adds specific holsters, pouches, cabling, or belts attached cleanly to body parts without loose clutter.',
      options: [
        'Holstered Sidearm & Pouch',
        'Shoulder Pauldrons & Cloak',
        'Fibre-Optic Cabling',
        'Ammunition Belts',
        'Scabbard & Strap Rig',
        'Scroll Tubes & Flasks',
        'Energy Battery Backpack',
        'Tattered Cape & Chain',
        'Medic Utility Pack',
      ],
    },
    {
      key: 'primary_colours',
      label: 'Primary Colours',
      tooltip: 'Dominant 60% color palette choices. Guides global albedo mapping for sprite shading.',
      options: [
        'Matte Charcoal Black & Gunmetal',
        'Royal Navy & Deep Silver',
        'Crimson Red & Black',
        'Emerald Green & Tan',
        'Midnight Violet & Indigo',
        'Sand Beige & Rust',
        'Pearl White & Chrome',
        'Deep Obsidian & Gold',
      ],
    },
    {
      key: 'accent_colours',
      label: 'Accent Colours',
      tooltip: 'High-contrast secondary colors (20%) for energy lines, eyes, trim, and magic glows.',
      options: [
        'Cyan Neon #06B6D4',
        'Polished Gold #F59E0B',
        'Electric Violet',
        'Safety Crimson',
        'Toxic Acid Green',
        'Plasma Cyan',
        'Molten Copper',
        'Spectral Rose',
        'Laser Yellow #EAB308',
      ],
    },
    {
      key: 'materials',
      label: 'Materials & Surfaces',
      tooltip: 'Defines how light interacts with surfaces (e.g. metallic reflections vs flat matte cloth).',
      options: [
        'Reinforced Composites & Alloy',
        'Burnished Steel & Leather',
        'Woven Silk & Runic Crystals',
        'Weathered Carbon Fibre',
        'Damascus Steel & Dragon Scale',
        'Polished Brass & Glass',
        'Etched Obsidian Plate',
        'Synthetic Polymer',
      ],
    },
    {
      key: 'exclusions',
      label: 'Explicit Exclusions',
      tooltip:
        'Strict negative rules passed to AI generator to prevent unrequested items, floor shadows, or clutter.',
      options: [
        'No weapons, no floor shadows',
        'No oversized pauldrons',
        'No cape, no facial features',
        'No glowing trails',
        'No floor terrain, no text labels',
        'No background clutter, no pets',
      ],
    },
    {
      key: 'additional_anatomy',
      label: 'Additional Genuine Anatomy',
      tooltip:
        'Extra anatomical components, each in its own sprite slot. Comma-separated, with ×N for how many of each — "Demon Horn ×2, Tail ×1" adds three components to the inventory and to the sheet’s stated count.',
      options: [
        NO_ADDITIONAL_ANATOMY,
        'Prehensile Cyber Tail ×1',
        'Mechanical Wing ×2',
        'Auxiliary Arm ×2',
        'Serpentine Tail ×1',
        'Feathered Archangel Wing ×2',
        'Demon Horn ×2, Tail ×1',
      ],
    },
  ],
};
