import { NO_ADDITIONAL_ANATOMY } from '../anatomy.ts';
import type { CategoryDefinition } from '../../types/subject.ts';

/** Monsters and beasts — non-humanoid limb layouts, biological rather than worn detail. */
export const CREATURE: CategoryDefinition = {
  label: 'Creature / Monster',
  fields: [
    {
      key: 'species',
      label: 'Creature Class',
      tooltip: 'Defines monster classification and limb layout (quadruped, insectoid, void entity).',
      options: [
        'Beast / Quadruped',
        'Mechanical Automaton',
        'Chitinous Insectoid',
        'Void Abomination',
        'Elemental Golem',
        'Draconic Drake',
        'Hydra Multi-Head',
        'Slime / Ooze Form',
        'Fungal Spore Monster',
        'Arachnid Swarmer',
      ],
    },
    {
      key: 'gender',
      label: 'Form Variant',
      tooltip: 'Specifies biological hierarchy or rank (alpha leader, worker minion, hive queen).',
      options: [
        'Apex Alpha',
        'Drone / Minion',
        'Queen / Hive Mother',
        'Elder Ancient',
        'Lesser Stalker',
        'Prime Matriarch',
        'Mutated Specimen',
        'Overlord Colossus',
      ],
    },
    {
      key: 'age',
      label: 'Vitality State',
      tooltip: 'Controls battle wear, corruption, or elemental intensity.',
      options: [
        'Prime Ferocity',
        'Ancient Weathered',
        'Freshly Spawned',
        'Corrupted Corpse',
        'Enraged Overclocked',
        'Slumbering Dormant',
        'Mutated Hyper-Growth',
      ],
    },
    {
      key: 'role',
      label: 'Combat Behaviour',
      tooltip: 'Informs creature stance, mandible open state, and aggressive pose capability.',
      options: [
        'Ambusher Pouncer',
        'Frontline Tank Swarmer',
        'Ranged Spitter',
        'Flying Harasser',
        'Burrowing Surprise Attacker',
        'Support Aura Emitter',
        'Area Denier',
        'Apex Predator',
      ],
    },
    {
      key: 'setting',
      label: 'Habitat / Theme',
      tooltip: 'Establishes environment context for biological camouflage and shell textures.',
      options: [
        'Alien Hive Core',
        'Volcanic Caverns',
        'Deep Space Derelict',
        'Fungal Swamplands',
        'Glacial Ice Trench',
        'Subterranean Ruins',
        'Radioactive Wasteland',
        'Toxic Sewers',
      ],
    },
    {
      key: 'build',
      label: 'Mass & Frame',
      tooltip: 'Defines carapace thickness, spine arrangement, and physical weight distribution.',
      options: [
        'Low-Slung Quadruped',
        'Huge Heavy Carapace',
        'Slender Serpent-like',
        'Multi-Legged Walker',
        'Massive Winged Fiend',
        'Amorphous Blob Frame',
        'Skeletal Centipede',
      ],
    },
    {
      key: 'silhouette',
      label: 'Spines & Silhouette',
      tooltip: 'Focuses outward spikes, shell plates, and distinctive creature outline.',
      options: [
        'Jagged Dorsal Spines',
        'Segmented Shell Plates',
        'Tentacled Mass',
        'Crystalline Outcrops',
        'Spike-Covered Back',
        'Humped Carapace',
        'Webbed Wing Membrane',
      ],
    },
    {
      key: 'face_head',
      label: 'Mandibles & Sensory',
      tooltip: 'Configures eyes, fangs, mouth parts, and sensory feelers.',
      options: [
        'Triple Jaw Mandibles',
        'Compound Insect Eyes',
        'Single Glowing Monocular Sensor',
        'Fanged Maw',
        'Eyeless Sensing Slits',
        'Multi-Horned Skull',
        'Acid Siphon Maw',
      ],
    },
    {
      key: 'anatomy',
      label: 'Anatomy Base',
      tooltip: 'Controls how monster body parts are broken down into isolated components.',
      options: [
        'QUADRUPED BEAST',
        'HEXAPOD INSECT',
        'SERPENTINE TAILLESS',
        'BIPEDAL BEAST',
        'OCTOPUS TENTACLED',
        'CENTIPEDE MULTI-SEGMENT',
      ],
    },
    {
      key: 'clothing',
      label: 'Harness / Augments',
      tooltip: 'Adds mounted weaponry, saddle straps, or cybernetic implants to the creature.',
      options: [
        'NONE',
        'Mounted Energy Cannons',
        'Reinforced Restraint Chains',
        'Saddle & Armor Harness',
        'Control Mind Spike',
        'Cybernetic Leg Armor',
      ],
    },
    {
      key: 'worn_details',
      label: 'Biological Marks',
      tooltip: 'Specifies bioluminescence patterns, acid drips, or scar tissue.',
      options: [
        'Bioluminescent Veins',
        'Battle Scars & Missing Scales',
        'Acidic Drip Droplets',
        'Chitin Cracks',
        'Glow Spore Clusters',
        'Molten Core Cracks',
        'Frost Crystal Coating',
      ],
    },
    {
      key: 'primary_colours',
      label: 'Primary Colours',
      tooltip: 'Main body/hide base colors.',
      options: [
        'Obsidian Black & Deep Purple',
        'Toxic Hive Yellow #EAB308 & Brown',
        'Albino White & Pale Pink',
        'Rusty Iron & Moss',
        'Crimson Red & Charcoal',
        'Deep Sea Cyan #06B6D4 & Navy',
        'Bio-Green #10B981 & Slate',
      ],
    },
    {
      key: 'accent_colours',
      label: 'Accent Colours',
      tooltip: 'High-visibility bio-luminescent or warning accent colors.',
      options: [
        'Acidic Lime Green #84CC16',
        'Magma Orange Glow #F97316',
        'Plasma Cyan #22D3EE',
        'Bio-Violet #8B5CF6',
        'Electric Yellow #EAB308',
        'Infrared Pink #F43F5E',
        'Stasis Blue #3B82F6',
      ],
    },
    {
      key: 'materials',
      label: 'Surface Shell',
      tooltip: 'Defines hide texture (wet chitin, rocky scales, translucent slime).',
      options: [
        'Hard Chitin Shell & Wet Membranes',
        'Molten Rock & Obsidian',
        'Rusting Scrap & Wiring',
        'Leathery Hide',
        'Scaly Dragon Hide',
        'Transparent Jelly Shell',
        'Frozen Ice Plating',
      ],
    },
    {
      key: 'exclusions',
      label: 'Explicit Exclusions',
      tooltip: 'Prevents unwanted human features or props from appearing on monster sheets.',
      options: [
        'No human clothing, no weapons',
        'No wings, no extra eyes',
        'No saddles, no mechanical parts',
        'No rider, no floor shadows',
        'No background text',
      ],
    },
    {
      key: 'additional_anatomy',
      label: 'Extra Appendages',
      tooltip:
        'Separate tails, stingers or blade-arms for modular animation. Comma-separated, with ×N for how many of each — "Blade Arm ×2, Sting Tail ×1" adds three components to the inventory and to the sheet’s stated count.',
      options: [
        NO_ADDITIONAL_ANATOMY,
        'Scorpion Sting Tail ×1',
        'Chitinous Blade Arm ×2',
        'Insectoid Wing ×4',
        'Prehensile Tentacle ×2',
        'Spike Tail Club ×1',
      ],
    },
  ],
};
