import { NO_ADDITIONAL_ANATOMY } from '../anatomy.ts';
import {
  ASSEMBLY_BASE_CHOOSES_THE_SHEETS,
  HEX_CODE_PINS_THE_HUE,
  SUBJECT_TYPE_ADDS_NO_COMPONENTS,
} from '../guidanceSentences.ts';
import type { CategoryDefinition } from '../../types/subject.ts';

/** Monsters and beasts — non-humanoid limb layouts, biological rather than worn detail. */
export const CREATURE: CategoryDefinition = {
  label: 'Creature / Monster',
  article: 'a',
  fields: [
    {
      key: 'species',
      label: 'Creature Class',
      tooltip:
        'The monster classification, which decides the body the creature is drawn with. A quadruped, an insectoid and a void entity differ in how they stand, where their weight sits and what reads first. Set this before the anatomy base, which should agree with it.\n\n' +
        SUBJECT_TYPE_ADDS_NO_COMPONENTS,
      options: [
        'Beast / Quadruped',
        'Mechanical Automaton',
        'Chitinous Insectoid',
        'Void Abomination',
        'Elemental Golem',
        'Draconic Drake',
        'Hydra Multi-Head',
        'Slime / Ooze Form',
        'Fungal Spore Monster',
        'Arachnid Swarmer',
        'Avian Raptor',
        'Crystalline Shardling',
        'Strangling Vine Growth',
        'Bone Construct',
        'Domestic Livestock',
        'Amphibian Croaker',
        'Subterranean Burrower',
        'Cephalopod Crawler',
        'Feathered Pack Runner',
      ],
    },
    {
      key: 'gender',
      label: 'Form Variant',
      tooltip:
        'Where this specimen sits in its own hierarchy. Rank reads as scale and ornament: a hive queen carries more mass, silhouette and distinguishing marks than a drone of the same species, and is still the same creature.',
      options: [
        'Apex Alpha',
        'Drone / Minion',
        'Queen / Hive Mother',
        'Elder Ancient',
        'Lesser Stalker',
        'Prime Matriarch',
        'Mutated Specimen',
        'Overlord Colossus',
        'Juvenile Whelp',
        'Twin-Bonded Pair',
      ],
    },
    {
      key: 'age',
      label: 'Vitality State',
      tooltip:
        'The creature’s condition: battle wear, corruption, or how hard its elemental core is running. It shifts surface damage and glow across every component at once, so a freshly spawned and an ancient variant of one design read as a set.',
      options: [
        'Prime Ferocity',
        'Ancient Weathered',
        'Freshly Spawned',
        'Corrupted Corpse',
        'Enraged Overclocked',
        'Slumbering Dormant',
        'Mutated Hyper-Growth',
        'Starved & Emaciated',
        'Well-Fed & Placid',
        'Wounded & Limping',
      ],
    },
    {
      key: 'role',
      label: 'Combat Behaviour',
      tooltip:
        'What the creature does in a fight. It sets the rest stance the components are drawn in, such as mandibles open or closed and weight forward or coiled, and so how much of the pose is baked in before you animate.',
      options: [
        'Ambusher Pouncer',
        'Frontline Tank Swarmer',
        'Ranged Spitter',
        'Flying Harasser',
        'Burrowing Surprise Attacker',
        'Support Aura Emitter',
        'Area Denier',
        'Apex Predator',
        // Not everything on a creature sheet fights. A herd animal, a mount and a nest-sitter each
        // want a different stance, and asking for "combat behaviour" from a pig produces a snarl.
        'Herd Animal / Non-Combatant',
        'Mount / Beast Of Burden',
        'Nest Guardian',
        'Scavenger Carrion Eater',
        'Pack Hunter — Flanker',
        'Sentry & Alarm Raiser',
        'Brood Host',
      ],
    },
    {
      key: 'setting',
      label: 'Habitat / Theme',
      tooltip:
        'Where the creature lives. Habitat drives camouflage colouring and shell texture more strongly than any colour field, because it tells the generator what the animal evolved against.',
      options: [
        'Alien Hive Core',
        'Volcanic Caverns',
        'Deep Space Derelict',
        'Fungal Swamplands',
        'Glacial Ice Trench',
        'Subterranean Ruins',
        'Radioactive Wasteland',
        'Toxic Sewers',
        'Coral Reef Shallows',
        'Highland Moor',
        'Sky Island Updrafts',
        'Abandoned Farmstead',
        'Temperate Woodland',
        'Desert Salt Pan',
        'Storm-Wracked Coast',
      ],
    },
    {
      key: 'build',
      label: 'Mass & Frame',
      tooltip:
        'The frame the mass is carried on: carapace thickness, spine arrangement, weight distribution. It sets each component’s footprint, so a low-slung quadruped packs into an atlas very differently from a towering winged fiend.',
      options: [
        'Low-Slung Quadruped',
        'Huge Heavy Carapace',
        'Slender Serpent-Like',
        'Multi-Legged Walker',
        'Massive Winged Fiend',
        'Amorphous Blob Frame',
        'Skeletal Centipede',
        'Rounded Barrel Body',
        'Bipedal Raptor Stance',
        'Winged Serpent Coil',
        'Tiny Swarm Individual',
        'Broad Digging Forelimbs',
        'Long-Necked Grazer Frame',
        'Flattened Ambush Body',
      ],
    },
    {
      key: 'silhouette',
      label: 'Spines & Silhouette',
      tooltip:
        'The outward profile: spikes, shell plates, membranes. It is the read at gameplay distance, and often the only cue that tells a dangerous variant from a harmless one before it attacks.',
      options: [
        'Jagged Dorsal Spines',
        'Segmented Shell Plates',
        'Tentacled Mass',
        'Crystalline Outcrops',
        'Spike-Covered Back',
        'Humped Carapace',
        'Webbed Wing Membrane',
        'Rounded Grazing Profile',
        'Feathered Ruff & Crest',
        'Branching Antler Crown',
        'Shovel Claws & Armoured Brow',
        'Smooth Finned Profile',
        'Drooping Fungal Caps',
      ],
    },
    {
      key: 'face_head',
      label: 'Mandibles & Sensory',
      tooltip:
        'Eyes, fangs, mouth parts and sensory organs. On a monster the head carries the threat signal, so be specific: compound insect eyes and eyeless sensing slits give entirely different silhouettes at the same size.',
      options: [
        'Triple Jaw Mandibles',
        'Compound Insect Eyes',
        'Single Glowing Monocular Sensor',
        'Fanged Maw',
        'Eyeless Sensing Slits',
        'Multi-Horned Skull',
        'Acid Siphon Maw',
        'Blunt Snout & Flop Ears',
        'Hooked Raptor Beak',
        'Antlered Herbivore Skull',
        'Bioluminescent Lure Stalk',
        'Eyeless Digging Snout',
        'Petalled Maw & Pollen Vents',
        'Whiskered Muzzle & Wet Nose',
        'Beaked Cephalopod Mouth',
        'Frilled Neck & Warning Display',
      ],
      oneSidedOptions: {
        'Single Glowing Monocular Sensor': 'single glowing monocular sensor',
      },
    },
    {
      key: 'anatomy',
      label: 'Anatomy Base',
      tooltip:
        'The body plan the creature is drawn on, and the pieces it is cut into: `Hexapod Insect` walks on six legs and `Eight-Legged Arachnid` on eight, `Serpentine Tailless` is a head over body segments, and `Multi-Headed Hydra Stems` draws one set of neck and head pieces that every neck is built from.\n\n' +
        'Choose the base that matches the Creature Class, such as `Eight-Legged Arachnid` for an `Arachnid Swarmer`.\n\n' +
        ASSEMBLY_BASE_CHOOSES_THE_SHEETS +
        '\n\nA piece the body plan does not draw, such as a sting tail or a second pair of wings, goes in Extra Appendages, the field that adds a slot for it.',
      options: [
        'Quadruped Beast',
        'Hexapod Insect',
        'Eight-Legged Arachnid',
        'Serpentine Tailless',
        'Bipedal Beast',
        'Octopus Tentacled',
        'Centipede Multi-Segment',
        'Winged Biped — Avian',
        'Rooted Stationary Growth',
        'Amorphous — No Fixed Limbs',
        'Burrowing Segmented Worm',
        'Finned Aquatic Body',
        'Multi-Headed Hydra Stems',
      ],
    },
    {
      key: 'clothing',
      label: 'Harness / Augments',
      tooltip:
        'Mounted weaponry, restraint chains, saddles or cybernetics fitted to the creature. Everything here reads as imposed on the animal rather than grown by it, so choose `NONE` for a purely biological beast.',
      options: [
        'NONE',
        'Mounted Energy Cannons',
        'Reinforced Restraint Chains',
        'Saddle & Armour Harness',
        'Control Mind Spike',
        'Cybernetic Leg Armour',
        'Branded Herd Tags',
        'Muzzle & Restraint Harness',
        'Packed Panniers & Bedroll',
        'Woven Pack Bags & Girth Strap',
        'Bell Collar & Lead Rope',
        'Grafted Bio-Armour Plates',
      ],
      absentOption: 'NONE',
    },
    {
      key: 'worn_details',
      label: 'Biological Marks',
      tooltip:
        'The marks the creature carries: bioluminescence, acid drips, scarring, shell cracks. They sell the surface as living tissue rather than a painted shell, and they are the first details lost when the sprite is scaled down.',
      options: [
        'Bioluminescent Veins',
        'Battle Scars & Missing Scales',
        'Acidic Drip Droplets',
        'Chitin Cracks',
        'Glow Spore Clusters',
        'Molten Core Cracks',
        'Frost Crystal Coating',
        'Mud Splatter & Straw',
        'Moulting Patchy Fur',
        'Barnacle Encrustation',
        'Healed Brand Scar',
        'Carrion Stains & Circling Flies',
        'Nest Debris & Shell Fragments',
        'Venom Spurs & Wet Glands',
        'Territorial Claw Rakes',
      ],
      oneSidedOptions: {
        'Healed Brand Scar': 'healed brand scar',
      },
    },
    {
      key: 'primary_colours',
      label: 'Primary Colours',
      tooltip:
        'The base hide, shell or carapace colours carried across the whole creature. Two colours with a clear value gap survive downscaling, where a single flat hide colour tends to collapse into a silhouette.',
      options: [
        'Obsidian Black & Deep Purple',
        'Toxic Hive Yellow #EAB308 & Brown',
        'Albino White & Pale Pink',
        'Rusty Iron & Moss',
        'Crimson Red & Charcoal',
        'Deep Sea Cyan #06B6D4 & Navy',
        'Bio-Green #10B981 & Slate',
        'Warm Pink Hide & Sable Patches',
        'Bleached Coral & Bruised Violet',
        'Heather Brown & Oat Cream',
        'Sand Dun & Chalk Underbelly',
        'Ink Black & Cold Silver',
        'Amber Chitin & Umber Bands',
      ],
    },
    {
      key: 'accent_colours',
      label: 'Accent Colours',
      tooltip:
        'The bioluminescent or warning colours, meant to be seen and understood instantly. ' +
        HEX_CODE_PINS_THE_HUE,
      options: [
        'Acidic Lime Green #84CC16',
        'Magma Orange Glow #F97316',
        'Plasma Cyan #22D3EE',
        'Bio-Violet #8B5CF6',
        'Electric Yellow #EAB308',
        'Infrared Pink #F43F5E',
        'Stasis Blue #3B82F6',
        'Trough Slop Brown',
        'Dawn Feather Gold #F59E0B',
        'No Accent — Naturalistic Only',
        'Warning Scarlet #DC2626',
        'Pollen Gold #FACC15',
        'Cold Ice Blue #7DD3FC',
      ],
    },
    {
      key: 'materials',
      label: 'Surface Shell',
      tooltip:
        'The hide texture and how light behaves on it: wet chitin catches a hard highlight, rocky scale scatters it, translucent jelly lets it through. It is often all that separates two creatures sharing a silhouette.',
      options: [
        'Hard Chitin Shell & Wet Membranes',
        'Molten Rock & Obsidian',
        'Rusting Scrap & Wiring',
        'Leathery Hide',
        'Scaly Dragon Hide',
        'Transparent Jelly Shell',
        'Frozen Ice Plating',
        'Bristled Hide & Wet Snout',
        'Calcified Coral & Wet Membrane',
        'Downy Feather & Keratin',
        'Waxy Plant Cuticle',
        'Faceted Crystal & Mineral Vein',
        'Dry Bone & Sinew Lash',
        'Damp Permeable Skin & Slime',
        'Matted Fur & Caked Mud',
      ],
    },
    {
      key: 'exclusions',
      label: 'Explicit Exclusions',
      tooltip:
        'Negative rules that keep human features, gear and scene dressing off a monster sheet. Name riders and floor shadows: each attaches something to the creature that cannot be cut away once it is drawn.',
      options: [
        'No human clothing, no weapons',
        'No extra wings, no extra eyes',
        'No saddles, no mechanical parts',
        'No rider, no floor shadows',
        'No background text',
        'No human clothing, no weapons, no rider, no floor shadows',
        'No rider, no floor shadows, no reins held taut',
        'No anthropomorphic face, no clothing',
        'No harness, no tack, no branded mark',
        'No glowing eyes, no emissive markings',
        'No spilled blood, no gore',
      ],
    },
    {
      key: 'additional_anatomy',
      label: 'Extra Appendages',
      tooltip:
        'Extra appendages, such as a sting tail, blade arms or another wing pair, each requested as its own sprite slot so you can animate it apart from the body.\n\n' +
        'List them with commas and `×N` for how many of each: “Blade Arm ×2, Sting Tail ×1” names three pieces, each drawn at every facing the sheet covers. On a five-view directional core that is fifteen components; on a single-facing sheet, three.',
      options: [
        NO_ADDITIONAL_ANATOMY,
        'Scorpion Sting Tail ×1',
        'Chitinous Blade Arm ×2',
        'Insectoid Wing ×4',
        'Prehensile Tentacle ×2',
        'Spike Tail Club ×1',
        'Prehensile Tentacle ×4, Polyp Cluster ×2',
        'Empty Saddle ×1, Stirrup ×2, Rein Strap ×1',
        'Feathered Crest ×1, Tail Fan ×1',
        'Antler Rack ×2',
        'Digging Claw ×2',
        'Egg Sac ×2',
        'Dorsal Fin ×1',
        'Spore Vent ×3',
      ],
    },
  ],
};
