import { NO_ADDITIONAL_ANATOMY } from '../anatomy.ts';
import { HEX_CODE_PINS_THE_HUE } from '../guidanceSentences.ts';
import type { CategoryDefinition } from '../../types/subject.ts';

/**
 * Interactive props — terminals, chests, turrets. Hard-surface geometry rather than anatomy.
 *
 * The source application left the last three fields without tooltips; they are written here in
 * the same voice, because a field with no tooltip renders no ⓘ at all and the specification
 * calls for guidance on every field.
 */
export const OBJECT: CategoryDefinition = {
  label: 'Interactive Object / Prop',
  article: 'an',
  fields: [
    {
      key: 'species',
      label: 'Object Category',
      tooltip:
        'What the prop fundamentally is. It decides the component breakdown as much as the look — a hinged chest, a turret and a wall panel share no parts at all — so set it before the structure base below.',
      options: [
        'Interactive Terminal',
        'Loot Chest / Container',
        'Power Generator',
        'Defense Turret',
        'Portal Gate',
        'Healing Station',
        'Vending Machine',
        'Control Console',
        'Ancient Relic Shrine',
        // Not every prop is a machine to interact with. An effect and a legibility test both want the
        // hard-surface field labels this category gives them and have nowhere else to live. A vehicle
        // does have somewhere — VEHICLE, which exists because a hull, a drive and a turning mount do
        // not decompose the way a housing, a footing and a hinged panel do — so it does not go here.
        'Explosion Burst Effect',
        'Weather Particle Sheet',
        'Silhouette Legibility Test',
        'Pressure Plate Trap',
        'Campfire & Cooking Pot',
        'Signpost & Notice Board',
        'Conveyor Belt Segment',
        'Ladder / Climbable Rung Set',
        'Crank Winch & Chain',
        'Water Well & Winch',
        'Workbench & Tool Rack',
        'Brazier / Standing Lamp',
      ],
    },
    {
      key: 'gender',
      label: 'Operational Status',
      tooltip:
        'Whether the object is working, damaged, sealed or overloading. It reads mostly as emissive state and damage — a powered-down console loses its glow entirely — which is what makes a paired on/off variant of one prop worth generating.',
      options: [
        'Fully Functional',
        'Damaged / Repaired',
        'Ancient Sealed',
        'Overclocked / Active',
        'Power Offline',
        'Corrupted Glitching',
        'Self-Destruct Sequence',
        'Mid-Destruction Frame',
        'Charging / Spooling Up',
        'Buried & Partly Excavated',
        'Newly Installed & Unused',
        'Sealed & Awaiting A Key',
        'Looted & Emptied',
      ],
    },
    {
      key: 'age',
      label: 'Tech Era',
      tooltip:
        'The design language the object is built in. It governs panel shapes, fastener style and material vocabulary across every component at once, which is what keeps a prop consistent with the world it is dropped into.',
      options: [
        'Futuristic Sci-Fi',
        'Ancient Magitech',
        'Retro 80s Industrial',
        'Medieval Wood & Iron',
        'Steampunk Brass',
        'Alien Crystal Tech',
        'Post-Apocalyptic Scraps',
        'Bronze Age Ritual',
        'Modern Municipal',
        'Deep-Sea Salvage',
        'Iron Age Rustic',
        'Clean Corporate Minimal',
      ],
    },
    {
      key: 'role',
      label: 'Game Function',
      tooltip:
        'What the object does for the player. It drives the indicators that make that legible without a label — healing greens, hazard reds, objective markers — so the prop’s purpose reads before anyone interacts with it.',
      options: [
        'Save Station / Healer',
        'High-Tier Loot Source',
        'Hazard Obstacle',
        'Objective Device',
        'Resource Converter',
        'Security Gateway',
        'Ammunition Recharger',
        'Traversal Aid',
        'Checkpoint / Respawn Anchor',
        'Trap / Ambush Trigger',
        'Light Source',
        'Storage & Stash Point',
        'Puzzle Mechanism',
      ],
    },
    {
      key: 'setting',
      label: 'Environment Context',
      tooltip:
        'The space the object is installed in. Its surroundings show up on the housing as grime, frost or neon spill, and that is what makes a prop look like it belongs somewhere rather than like it was dropped in.',
      options: [
        'Command Bridge',
        'Dungeon Chamber',
        'Cyber City Alley',
        'Abandoned Lab',
        'Temple Vault',
        'Space Station Engine Room',
        'Industrial Factory',
        'Snowy Mountain Pass',
        'Rain-Slicked Rooftop',
        'Farmyard & Barn',
        'Underground Mine Shaft',
        'Coral Shelf Seabed',
        'Village Square',
        'Ruined Cathedral Nave',
        'Desert Waystation',
      ],
    },
    {
      key: 'build',
      label: 'Form Factor',
      tooltip:
        'The physical geometry and volume — a pillar, a tabletop unit, a wall panel. It fixes how the object occupies space, and therefore its cell proportions in the atlas and whether it can sit on a floor tile at all.',
      options: [
        'Heavy Heavy Pillar',
        'Compact Tabletop Device',
        'Modular Wall Panel',
        'Spherical Pod',
        'Cylindrical Conduit',
        'Pyramidal Structure',
        'Wall-Mounted Box',
        'Flat Floor Inlay',
        'Suspended Ceiling Fixture',
        'Tall Narrow Post',
        'Low Wide Plinth Block',
        'Sunken Floor Pit',
      ],
    },
    {
      key: 'silhouette',
      label: 'Hard Surfaces',
      tooltip:
        'The edge profile of the casing — chamfered, gothic, sleek pod. Hard-surface props live or die on this: interior detail vanishes at sprite scale, while a distinctive corner treatment is still readable.',
      options: [
        'Chamfered Rectangular Box',
        'Pyramidal Conduit',
        'Cylindrical Core',
        'Asymmetric Mechanical',
        'Ornate Gothic Arches',
        'Sleek Oval Pod',
        'Hexagonal Tower',
        'Ragged Expanding Ring',
        'Fine Streaks & Flecks',
        'Lattice Frame & Struts',
        'Coiled Rope & Hook',
        'Ribbed Barrel & Domed Cap',
        'Stepped Ziggurat Tiers',
        'Splayed Tripod Legs',
      ],
    },
    {
      key: 'face_head',
      label: 'Interface Screen',
      tooltip:
        'The focal display — the part the eye goes to first. One bright interface reads better at sprite scale than several small ones, and it is usually the only component that needs an emissive colour at all.',
      options: [
        'Holographic Display Screen',
        'Analog Dials & Gauge Panels',
        'Runic Crystal Core',
        'Keypad & Biometric Scanner',
        'Glowing Monitor Array',
        'Lever & Valve Array',
        'White-Hot Core Flash',
        'Painted Cargo Panel',
        'Open Flame & Cook Pot',
        // For a sheet whose subject has no focal element at all — an effect, a particle set, a
        // silhouette pass — because leaving the field empty would invite one to be invented.
        'No Focal Feature',
        'Glass Lantern Housing & Wick',
        'Carved Stone Face & Offering Bowl',
        'Rope Drum & Hand Crank',
      ],
      oneSidedOptions: {
        'Rope Drum & Hand Crank': 'hand crank',
      },
    },
    {
      key: 'anatomy',
      label: 'Structure Base',
      tooltip:
        'How the object is broken into isolated components. Single Rigid Object emits one piece; the multi-segment and hinged plans split out the parts that actually move, so choose by what has to animate rather than by how complex the prop looks.',
      options: [
        'Single Rigid Object',
        'Multi-Segment Turret',
        'Hinged Chest Container',
        'Modular Conduit',
        'Rotating Spherical Core',
        'Break-Apart Shard Set',
        'Particle Frame Sequence',
        'Two-Part Lid And Base',
        'Telescoping Extendable Mast',
      ],
    },
    {
      key: 'clothing',
      label: 'Mounting / Framework',
      tooltip:
        'How the object is fixed in place — bolted, caged, suspended, freestanding. The mount is drawn as part of the prop, so it also decides where the prop can legally be placed once it is in a level.',
      options: [
        'Floor Bolted Frame',
        'Reinforced Steel Cage',
        'Suspended Cable Rig',
        'Freestanding Base',
        'Wall-Anchored Brackets',
        'Hydraulic Lift Feet',
        'Ceiling Chain Mount',
        'Buried Foundation Plinth',
        'Rope Lashed To A Post',
        'Sled Skids & Drag Rope',
      ],
    },
    {
      key: 'worn_details',
      label: 'Utility Markings',
      tooltip:
        'Hazard stripes, chevrons, engravings, exposed cabling and wear. These are what make an industrial prop believable, but each costs palette budget — a few well-placed marks read better than full coverage.',
      options: [
        'Hazard Stripes & Decals',
        'Warning Chevrons & LEDs',
        'Runic Engravings',
        'Coolant Pipe Joints',
        'Exposed Circuit Wiring',
        'Spray-Paint Marks & Scratches',
        'Moss & Vines',
        'Ember Sparks & Shockwave Ring',
        'Splash Crowns & Settle Drifts',
        'Soot Scorch Ring',
        'Rope Fray & Knots',
        'No Surface Detail At All',
        'Trigger Wire & Hidden Seam',
        'Chalk Tally Marks',
        'Wax Drips & Guttered Stubs',
      ],
    },
    {
      key: 'primary_colours',
      label: 'Primary Colours',
      tooltip:
        'The structural casing colours — what a prop is recognised by in a busy scene. Two colours with a clear value gap keep the object separable from whatever it is standing against.',
      options: [
        'Industrial Yellow #EAB308 & Charcoal',
        'Matte White & Dark Slate',
        'Weathered Bronze & Teak',
        'Deep Cobalt Blue #1E3A8A',
        'Gunmetal Grey & Orange',
        'Rusted Iron & Olive',
        'Gilded Gold #F59E0B & Marble',
        'Molten Orange #F97316 & Deep Charcoal',
        'Pale Frost White & Storm Grey',
        'Weathered Pine & Rust Iron',
        'Pure Black Fill',
        'Blackened Iron & Warm Oak',
        'Chalk White & Sea Blue',
        'Verdigris Copper & Grey Stone',
      ],
    },
    {
      key: 'accent_colours',
      label: 'Accent Colours',
      tooltip:
        'The status LEDs, wiring and screen light — the parts that read as emitting rather than reflecting. ' +
        HEX_CODE_PINS_THE_HUE,
      options: [
        'Alert Orange LEDs #F97316',
        'Laser Green Glow #10B981',
        'Stasis Blue Core #3B82F6',
        'Crimson Warning Strip #EF4444',
        'Neon Cyan Cables #06B6D4',
        'Arcane Purple Gem #8B5CF6',
        'Hot Pink Glitch #F43F5E',
        'White-Hot Core #FFFFFF',
        'Rain Sheen Blue #3B82F6',
        'No Accent, Fill Only',
        'Candle Flame Yellow #FBBF24',
        'Rune Gold Glow #D4AF37',
        'Sickly Poison Green #84CC16',
      ],
    },
    {
      key: 'materials',
      label: 'Material Plating',
      tooltip:
        'What the casing is made of, and how light reads off it: painted metal takes a soft sheen, polished brass a hard one, cut stone none at all. Under flat neutral lighting this is what still separates one surface from the next.',
      options: [
        'Painted Sheet Metal & Acrylic',
        'Polished Brass & Oak',
        'Carbon Composite & Glass',
        'Cast Iron',
        'Carved Granite & Crystal',
        'Reflective Mirror Alloy',
        'Incandescent Plasma & Soot',
        'Translucent Water & Ice',
        'Splintered Timber & Banded Steel',
        'Flat Fill, No Material Read',
        'Rope, Canvas & Tarred Timber',
        'Fired Clay & Glazed Tile',
        'Woven Wicker & Iron Bands',
      ],
    },
    {
      key: 'exclusions',
      label: 'Explicit Exclusions',
      tooltip:
        'Negative rules keeping operators, ground fixtures and scene dressing out of the sheet. Floor cables and pedestals are the usual offenders — each anchors the prop to a surface it may never actually be placed on.',
      options: [
        'No living character, no shadows',
        'No cables on floor',
        'No text or letters',
        'No pedestal or ground grid',
        'No ambient smoke',
        'No floor shadow, no debris props, no lens flare',
        'No ground terrain tiles, no characters, no sky gradient',
        'No living character, no shadows, no ground grid',
        'No living character, no cables on floor, no ground grid',
        'No internal detail, no outline, no gradient, no highlights',
        'No flame, no smoke, no embers',
        'No coins or loot spilling out',
        'No rope running off the sheet edge',
      ],
    },
    {
      key: 'additional_anatomy',
      label: 'Deployable Modules',
      tooltip:
        'Extra moving parts — dishes, clamps, vents, barrels — each isolated into its own sprite slot so it can animate against a static body. Comma-separated, with ×N for how many of each: “Vent Flap ×2, Clamp ×1” names three pieces, each drawn at every facing the sheet covers — fifteen components on a five-view directional core, three on a single-facing sheet.',
      options: [
        NO_ADDITIONAL_ANATOMY,
        'Deployable Sensor Dish ×1',
        'Articulated Arm Clamp ×1',
        'Coolant Vent Flap ×2',
        'Deployable Turret Barrel ×1',
        'Holographic Emitter Wing ×2',
        'Shockwave Ring ×1, Ember Mote ×3',
        'Rain Streak ×4, Snow Flake ×4, Ash Mote ×4, Ground Splash ×2',
        'Intact Shell ×1, Cracked Shell ×1, Splinter Shard ×4',
        'Hanging Lantern ×1',
        'Chain Link Run ×4',
        'Loose Lid ×1',
        'Winch Handle ×1',
      ],
    },
  ],
};
