import { DEFAULT_OUTPUT_CONFIG } from '../output/index.ts';
import type { PresetArchetype } from '../../types/preset.ts';

/**
 * The archetype the studio opens on — the app boots into the Cyberpunk Katana Specialist rather
 * than an empty form, so the prompt preview has something real in it from the first paint.
 *
 * Bound to a name as well as being first in the list so the subject store can state what it starts
 * from without indexing the array: under `noUncheckedIndexedAccess` an index read is
 * `PresetArchetype | undefined`, and the store would need a fallback for a case that cannot happen.
 */
const CYBERPUNK_KATANA: PresetArchetype = {
  id: 'cyberpunk-katana',
  name: 'Cyberpunk Katana Specialist',
  category: 'CHARACTER',
  subject: {
    species: 'Cybernetic Cyborg',
    gender: 'Feminine',
    age: 'Young Adult (20s)',
    role: 'Katana Specialist',
    setting: 'Cyberpunk Dystopia',
    build: 'Athletic & Slender',
    silhouette: 'Dynamic Sharp Edges',
    face_head: 'Neon Visor & Undercut',
    anatomy: 'STANDARD HUMANOID',
    clothing: 'Tactical Kevlar & Plates',
    worn_details: 'Holstered Sidearm & Pouch',
    primary_colours: 'Matte Charcoal Black & Gunmetal',
    accent_colours: 'Cyan Neon #06B6D4',
    materials: 'Reinforced Composites & Alloy',
    exclusions: 'No weapons, no floor shadows',
    additional_anatomy: 'NONE',
  },
  output: {
    ...DEFAULT_OUTPUT_CONFIG,
    directionalMode: 'CORE_DIRECTIONAL_VARIANTS',
    surfaceDetail: 'CLEAN_PRODUCTION',
    resolutionProfile: 'HIGH_RESOLUTION',
    paletteLimit: 'RESTRAINED_64_COLOR',
    outlineStyle: 'DARK_LOCAL_CONTOUR',
    lightingModel: 'FLAT_NEUTRAL_ALBEDO',
    aspectRatio: 'WIDE_16_9',
    targetModel: 'CHATGPT_5_6_SOL',
  },
};

/** The studio's opening state. See {@link CYBERPUNK_KATANA}. */
export const DEFAULT_PRESET = CYBERPUNK_KATANA;

/**
 * Built-in archetypes, spanning all five categories so each one has a worked example.
 *
 * These are complete subjects: every one of the sixteen fields is set, because a preset that
 * left gaps would compile a prompt containing `DEFINED` placeholders.
 */
export const BUILT_IN_ARCHETYPES: readonly PresetArchetype[] = [
  CYBERPUNK_KATANA,
  {
    id: 'scifi-marine',
    name: 'Sci-Fi Void Marine',
    category: 'CHARACTER',
    subject: {
      species: 'Human',
      gender: 'Masculine',
      age: 'Mature / Veteran (40s)',
      role: 'Heavy Mech Marine',
      setting: 'Grimdark Sci-Fi',
      build: 'Heavy Armoured Tank',
      silhouette: 'Bulky Plated Layers',
      face_head: 'Full Enclosed Helmet',
      anatomy: 'STANDARD HUMANOID',
      clothing: 'Gothic Plate Armour',
      worn_details: 'Shoulder Pauldrons & Cloak',
      primary_colours: 'Royal Navy & Deep Silver',
      accent_colours: 'Safety Crimson #EF4444',
      materials: 'Burnished Steel & Leather',
      exclusions: 'No cape, no facial features',
      additional_anatomy: 'NONE',
    },
    output: {
      ...DEFAULT_OUTPUT_CONFIG,
      directionalMode: 'CORE_DIRECTIONAL_VARIANTS',
      surfaceDetail: 'DETAILED_PRODUCTION',
      resolutionProfile: 'HIGH_RESOLUTION',
      paletteLimit: 'STRICT_32_COLOR',
      outlineStyle: 'PURE_BLACK_OUTLINE',
      lightingModel: 'ISOMETRIC_TOP_LEFT',
      aspectRatio: 'WIDE_16_9',
      targetModel: 'GENERIC',
    },
  },
  {
    id: 'dungeon-knight',
    name: 'Pixel Dungeon Knight',
    category: 'CHARACTER',
    subject: {
      species: 'Human',
      gender: 'Masculine',
      age: 'Young Adult (20s)',
      role: 'Paladin',
      setting: 'Dark Fantasy',
      build: 'Stocky & Robust',
      silhouette: 'Bulky Plated Layers',
      face_head: 'Braided Hair & Warpaint',
      anatomy: 'STANDARD HUMANOID',
      clothing: 'Gothic Plate Armour',
      worn_details: 'Shoulder Pauldrons & Cloak',
      primary_colours: 'Crimson Red & Black',
      accent_colours: 'Polished Gold #F59E0B',
      materials: 'Burnished Steel & Leather',
      exclusions: 'No floor shadows',
      additional_anatomy: 'NONE',
    },
    output: {
      ...DEFAULT_OUTPUT_CONFIG,
      directionalMode: 'CORE_DIRECTIONAL_VARIANTS',
      surfaceDetail: 'CLEAN_PRODUCTION',
      resolutionProfile: 'RETRO_16_BIT',
      paletteLimit: 'STRICT_32_COLOR',
      outlineStyle: 'DARK_LOCAL_CONTOUR',
      lightingModel: 'FLAT_NEUTRAL_ALBEDO',
      aspectRatio: 'SQUARE_1_1',
      targetModel: 'GENERIC',
    },
  },
  {
    id: 'creature-drone',
    name: 'Cybernetic Attack Drone',
    category: 'CREATURE',
    subject: {
      species: 'Mechanical Automaton',
      gender: 'Drone / Minion',
      age: 'Prime Ferocity',
      role: 'Flying Harasser',
      setting: 'Deep Space Derelict',
      build: 'Low-Slung Quadruped',
      silhouette: 'Segmented Shell Plates',
      face_head: 'Single Glowing Monocular Sensor',
      anatomy: 'QUADRUPED BEAST',
      clothing: 'Mounted Energy Cannons',
      worn_details: 'Bioluminescent Veins',
      primary_colours: 'Obsidian Black & Deep Purple',
      accent_colours: 'Plasma Cyan #22D3EE',
      materials: 'Rusting Scrap & Wiring',
      exclusions: 'No human clothing, no weapons',
      additional_anatomy: 'Double Pair Wings',
    },
    output: {
      ...DEFAULT_OUTPUT_CONFIG,
      directionalMode: 'CORE_DIRECTIONAL_VARIANTS',
      surfaceDetail: 'CLEAN_PRODUCTION',
      resolutionProfile: 'HIGH_RESOLUTION',
      paletteLimit: 'RESTRAINED_64_COLOR',
      outlineStyle: 'DARK_LOCAL_CONTOUR',
      lightingModel: 'FLAT_NEUTRAL_ALBEDO',
      aspectRatio: 'WIDE_16_9',
      targetModel: 'GENERIC',
    },
  },
  {
    id: 'prop-terminal',
    name: 'Sci-Fi Control Console',
    category: 'OBJECT',
    subject: {
      species: 'Interactive Terminal',
      gender: 'Fully Functional',
      age: 'Futuristic Sci-Fi',
      role: 'Objective Device',
      setting: 'Command Bridge',
      build: 'Compact Tabletop Device',
      silhouette: 'Chamfered Rectangular Box',
      face_head: 'Holographic Display Screen',
      anatomy: 'SINGLE RIGID OBJECT',
      clothing: 'Floor Bolted Frame',
      worn_details: 'Warning Stencils & LEDs',
      primary_colours: 'Matte White & Dark Slate',
      accent_colours: 'Alert Orange LEDs #F97316',
      materials: 'Carbon Composite & Glass',
      exclusions: 'No living character, no shadows',
      additional_anatomy: 'Deployable Sensor Dish',
    },
    output: {
      ...DEFAULT_OUTPUT_CONFIG,
      directionalMode: 'SINGLE_DIRECTION_POSE_LIBRARY',
      surfaceDetail: 'CLEAN_PRODUCTION',
      resolutionProfile: 'MID_RESOLUTION',
      paletteLimit: 'RESTRAINED_64_COLOR',
      outlineStyle: 'DARK_LOCAL_CONTOUR',
      lightingModel: 'UNLIT_EMISSIVE_BAKED',
      aspectRatio: 'SQUARE_1_1',
      targetModel: 'GENERIC',
    },
  },
  {
    id: 'building-ramen',
    name: 'Neo-Tokyo Ramen Kiosk',
    category: 'BUILDING',
    subject: {
      species: 'Ramen Stand Kiosk',
      gender: 'Active & In-Use',
      age: 'Neo-Tokyo Cyberpunk',
      role: 'Vendor / Shop Kiosk',
      setting: 'Rain-Slicked Neon Street',
      build: '1-Story Wide Kiosk',
      silhouette: 'Overhanging Neon Signage & Pipes',
      face_head: 'Open Counter & Bar Stools',
      anatomy: 'SINGLE STRUCTURE MODEL',
      clothing: 'Striped Fabric Awning',
      worn_details: 'Hanging Paper Lanterns & Cables',
      primary_colours: 'Dark Stained Wood & Vermilion Red #EA580C',
      accent_colours: 'Neon Pink Sign Glow #F43F5E',
      materials: 'Cedar Wood, Clay Tiles & Paper',
      exclusions: 'No ground terrain tiles, no characters',
      additional_anatomy: 'External Chimney & Smoke Pipe',
    },
    output: {
      ...DEFAULT_OUTPUT_CONFIG,
      directionalMode: 'SINGLE_DIRECTION_POSE_LIBRARY',
      surfaceDetail: 'DETAILED_PRODUCTION',
      resolutionProfile: 'HIGH_RESOLUTION',
      paletteLimit: 'EXPANDED_ALBEDO',
      outlineStyle: 'DARK_LOCAL_CONTOUR',
      lightingModel: 'FLAT_NEUTRAL_ALBEDO',
      aspectRatio: 'WIDE_16_9',
      targetModel: 'GENERIC',
    },
  },
];
