import { DEFAULT_IMAGE_CONFIG } from '../output/index.ts';
import { DEFAULT_CAMERA_ELEVATIONS } from '../promptText/index.ts';
import type { PresetArchetype } from '../../types/preset.ts';

/**
 * Whole structures — the buildings a level is made of one at a time rather than tiled.
 *
 * A building is one of the two categories whose default sheet is a tile field, so these four
 * deliberately take the other two plans: the module library, which delivers a façade as repeatable
 * bays, and the three-facing set, which delivers one structure turned. The tile-field presets live
 * next door in `buildingTilesets.ts`.
 */
export const BUILDING_STREET_PRESETS: readonly PresetArchetype[] = [
  {
    id: 'building-ramen',
    name: 'Neo-Tokyo Ramen Kiosk',
    category: 'BUILDING',
    subject: {
      species: 'Ramen Stand Kiosk',
      gender: 'Active & In-Use',
      age: 'Neo-Tokyo Cyberpunk',
      role: 'Vendor / Shop Kiosk',
      setting: 'Rain-Slicked Neon Street',
      build: '1-Story Wide Kiosk',
      silhouette: 'Overhanging Neon Signage & Pipes',
      face_head: 'Open Counter & Bar Stools',
      anatomy: 'SINGLE STRUCTURE MODEL',
      clothing: 'Striped Fabric Awning',
      worn_details: 'Hanging Paper Lanterns & Cables',
      primary_colours: 'Dark Stained Wood & Vermilion Red #EA580C',
      accent_colours: 'Neon Pink Sign Glow #F43F5E',
      materials: 'Cedar Wood, Clay Tiles & Paper',
      exclusions: 'No ground terrain tiles, no characters',
      additional_anatomy: 'External Chimney ×1, Smoke Pipe ×1',
    },
    output: {
      ...DEFAULT_IMAGE_CONFIG,
      directionalMode: 'SINGLE_DIRECTION_POSE_LIBRARY',
      surfaceDetail: 'DETAILED_PRODUCTION',
      resolutionProfile: 'HIGH_RESOLUTION',
      paletteLimit: 'EXPANDED_ALBEDO',
      outlineStyle: 'DARK_LOCAL_CONTOUR',
      lightingModel: 'FLAT_NEUTRAL_ALBEDO',
      aspectRatio: 'WIDE_16_9',
      targetModel: 'GENERIC',
    },
  },
  {
    id: 'oblique-shopfront-row',
    name: 'Oblique Shopfront Row',
    category: 'BUILDING',
    subject: {
      species: 'Cybernetics Clinic',
      gender: 'Active & In-Use',
      age: 'Neo-Tokyo Cyberpunk',
      role: 'Vendor / Shop Kiosk',
      setting: 'Rain-Slicked Neon Street',
      build: '2-Story Compact Footprint',
      silhouette: 'Overhanging Neon Signage & Pipes',
      face_head: 'Sliding Automated Glass',
      anatomy: 'MODULAR BUILDING TILES',
      clothing: 'Neon Holographic Banner',
      worn_details: 'Holographic Vending Sign',
      primary_colours: 'Concrete Slate & Blue Metal',
      accent_colours: 'Neon Pink Sign Glow #F43F5E',
      materials: 'Corrugated Iron & Glass',
      exclusions: 'No ground terrain tiles, no characters',
      additional_anatomy: 'Rooftop Antenna Rig ×1',
    },
    output: {
      ...DEFAULT_IMAGE_CONFIG,
      // Oblique keeps the shopfronts undistorted while still showing depth, which is what lets a row
      // of separate bays be laid side by side without the perspective disagreeing between them.
      projection: 'OBLIQUE_45',
      cameraElevation: DEFAULT_CAMERA_ELEVATIONS.OBLIQUE_45,
      directionalMode: 'SINGLE_DIRECTION_POSE_LIBRARY',
      directions: 'SINGLE_FRONT',
      resolutionProfile: 'MID_RESOLUTION',
      surfaceDetail: 'DETAILED_PRODUCTION',
      lightingModel: 'UNLIT_EMISSIVE_BAKED',
      rigMode: 'NONE',
      spriteTargetSize: '96 × 128 px per bay',
      aspectRatio: 'ULTRAWIDE_21_9',
      targetModel: 'GENERIC',
    },
  },
  {
    id: 'gothic-watchtower',
    name: 'Gothic Watchtower',
    category: 'BUILDING',
    subject: {
      species: 'Modular Watchtower',
      gender: 'Fortified Stronghold',
      age: 'Gothic Stone Fortress',
      role: 'Defense Tower Structure',
      setting: 'Snowy Mountain Pass',
      build: 'Tall 3-Tier Tower',
      silhouette: 'Battlements & Machicolations',
      face_head: 'Heavy Reinforced Oak Door',
      anatomy: 'TOWER WITH DETACHABLE ROOF',
      clothing: 'Gargoyle Corner Statues',
      worn_details: 'Wall Mounted Torches & Shield',
      primary_colours: 'Weathered Grey Stone & Oak',
      accent_colours: 'Torchfire Yellow #EAB308',
      materials: 'Cut Granite Blocks & Iron Girders',
      exclusions: 'No surrounding trees or sky',
      additional_anatomy: 'Defensive Turret Mount ×1',
    },
    output: {
      ...DEFAULT_IMAGE_CONFIG,
      projection: 'TRUE_ISOMETRIC',
      cameraElevation: DEFAULT_CAMERA_ELEVATIONS.TRUE_ISOMETRIC,
      directionalMode: 'CORE_DIRECTIONAL_VARIANTS',
      paletteLimit: 'EXPANDED_ALBEDO',
      surfaceDetail: 'TEXTURED',
      lightingModel: 'ISOMETRIC_TOP_LEFT',
      rigMode: 'NONE',
      // Tall, because the sheet's shape should match the subject's: three storeys turned three ways
      // packs into a portrait canvas and wastes most of a landscape one.
      aspectRatio: 'TALL_9_16',
      targetModel: 'GENERIC',
    },
  },
  {
    id: 'desert-outpost-pod',
    name: 'Desert Outpost Pod',
    category: 'BUILDING',
    subject: {
      species: 'Sci-Fi Landing Pad',
      gender: 'Under Construction',
      age: 'Sci-Fi Outpost Modular',
      role: 'Spawn Point',
      setting: 'Desert Wasteland',
      build: 'Miniature Outpost Pod',
      silhouette: 'Solar Glass Panels',
      face_head: 'Steel Blast Door',
      anatomy: 'SINGLE STRUCTURE MODEL',
      clothing: 'Solar Panel Array',
      worn_details: 'Exposed Air Conditioning Units',
      primary_colours: 'White Polymer & Glass',
      accent_colours: 'Plasma Cyan Stream #06B6D4',
      materials: 'Reinforced Concrete & Steel',
      exclusions: 'No floor shadow, no grid overlay',
      additional_anatomy: 'Rooftop Heli-Pad ×1',
    },
    output: {
      ...DEFAULT_IMAGE_CONFIG,
      renderStyle: 'RENDERED_3D',
      paletteLimit: 'UNRESTRICTED',
      outlineStyle: 'OUTLINE_LESS_ALBEDO',
      directionalMode: 'SINGLE_DIRECTION_POSE_LIBRARY',
      directions: 'SINGLE_FRONT',
      backgroundKey: 'TRANSPARENT',
      rigMode: 'NONE',
      aspectRatio: 'WIDE_16_9',
      targetModel: 'GEMINI_FLASH_IMAGE',
    },
  },
];
